### ISSUE TITLE
chore: remove dependency on engagement service

### ISSUE THREAD

**Issue by ngurenyaga** [savannahghi/mycarehub#104]
`deps.yml`

```yaml
staging:
  - depName: engagement
    depRootDomain: https://engagement-staging.healthcloud.co.ke
testing:
  - depName: engagement
    depRootDomain: https://engagement-testing.savannahghi.org
production:
  - depName: engagement
    depRootDomain: https://engagement-prod.savannahghi.org
```
